-- =============================================
-- File     : 03_usp_load_bronze.sql
-- Project  : IndusLoan Analytics Platform
-- Author   : Dhiraj Kumar
-- Phase    : 3 - Bronze Layer
-- Purpose  : Load data from raw.applications
--            into bronze.applications and
--            bronze.masked_attributes
--            Handles FULL and INCR load modes
--            Masks PII columns
--            Logs run to audit.pipeline_run_log
-- =============================================

USE IndusLoanDB;
GO

-- =============================================
-- Section 2 : Create Procedure with Parameters
-- =============================================
CREATE PROCEDURE bronze.usp_load_bronze
    -- Parameter 1 : Load type
    -- FULL = load all rows from raw
    -- INCR = load only new rows since last run
    @p_load_type        VARCHAR(10)         ='INCR',

    -- Parameter 2 : Business date of this run
    -- Defaults to today if not provided
    @p_run_date     DATE        = NULL,

    -- Parameter 3 : Environment
    -- DEV / UAT / PROD
    @p_env          VARCHAR(10)     = 'DEV'

AS
BEGIN

    -- =============================================
    -- Section 3 : Declare Variables
    -- Variables are like containers that hold
    -- values during procedure execution
    -- They exist only while procedure is running
    -- =============================================

    -- Holds the run_id generated by pipeline_run_log
    -- Every action in this procedure references this ID
    DECLARE @run_id             INT;

    -- Holds watermark value from last successful run
    -- We load only rows where App_Id > @watermark_start
    DECLARE @watermark_start            VARCHAR(100);

    -- Holds highest App_Id loaded in this run
    -- Saved back to watermark_control after success
    DECLARE @watermark_end      VARCHAR(100);

    -- Counts rows loaded into bronze.applications
    DECLARE @rows_loaded        INT = 0;

    -- Holds error message if something goes wrong
    DECLARE @error_message      VARCHAR(MAX);

    -- Set run date to today if not provided
    if @p_run_date is NULL
        SET @p_run_date = CAST(GETDATE() AS DATE);

    -- =============================================
    -- Section 4 : TRY Block
    -- TRY = attempt to run all code inside
    -- If anything fails jump to CATCH block
    -- Think of it like:
    -- TRY   = try to do this work
    -- CATCH = if anything goes wrong do this
    -- =============================================

    BEGIN TRY
          -- =========================================
        -- Step 1 : Log pipeline run start
        -- First thing we do is create a record
        -- in pipeline_run_log with status RUNNING
        -- This proves pipeline started even if
        -- it fails later
        -- =========================================

        INSERT INTO audit.pipeline_run_log (
            pipeline_name,
            p_load_type,
            p_run_date,
            p_env,
            start_time,
            [status]
        )

        VALUES (
            'bronze_load',
            @p_load_type,
            @p_run_date,
            @p_env,
            GETDATE(),
            'RUNNING'
        )

        -- Capture the run_id just created
        -- SCOPE_IDENTITY returns last inserted
        -- identity value in current session

        SET @run_id = SCOPE_IDENTITY();

        -- =========================================
        -- Step 2 : Read Watermark
        -- We read the last_watermark value from
        -- audit.watermark_control table
        -- This tells us where last run stopped
        -- Example: last run loaded up to App_Id 1999000
        -- This run will load App_Id > 1999000 only
        -- If first ever run watermark = '0'
        -- So all rows load because App_Id > 0
        -- =========================================

        SELECT @watermark_start = last_watermark
        FROM audit.watermark_control
        WHERE pipeline_name = 'applications';

        -- =========================================
        -- Step 3 : Decide FULL or INCR Load
        -- If @p_load_type = 'FULL'
        --    load ALL rows from raw
        --    ignore watermark
        --    used when we want fresh reload
        -- If @p_load_type = 'INCR'
        --    load only NEW rows since last run
        --    rows where App_Id > @watermark_start
        --    used for daily incremental loads
        -- =========================================


        IF @p_load_type = 'FULL'
        BEGIN
            -- Full load : clear bronze first
            -- Then reload everything fresh
            TRUNCATE TABLE bronze.applications;
            TRUNCATE TABLE bronze.masked_attributes;

            -- Reset watermark to zero
            -- So all rows qualify for reload

            SET @watermark_start = '0';
        END
        ELSE
        BEGIN
            PRINT 'INCR load selected — watermark : '
                + @watermark_start;
        END

        -- =========================================
        -- Step 4 : Load Data from Raw to Bronze
        -- INSERT INTO SELECT pattern
        -- Read from raw.applications
        -- Write to bronze.applications
        -- Filter by watermark for INCR load
        -- Add audit columns batch_id and timestamp
        -- Add record_hash for deduplication
        -- =========================================

        INSERT INTO bronze.applications (
            batch_id,
            load_timestamp,
            record_hash,
            App_Id,
            Customer_Name,
            Date_Of_Birth,
            PAN_No,
            Product,
            Campaign_Type,
            Decision,
            Decision_Date,
            Stage,
            Decline_Code,
            Sourcing_Channel,
            DSA_Code,
            DSE_Code,
            Secondary_DSE_Code,
            Scheme_Id,
            Appl_Running_Serial_No,
            Signed_Date,
            Sourcing_Branch_Code,
            Residence_City,
            Fee_Code,
            Loan_Amount,
            Mailing_City,
            Type_Of_Organization,
            You_Are
        )
        SELECT
            -- batch_id comes from run_id we created
            -- in Step 1 in pipeline_run_log
            -- This links every bronze row to its run
            @run_id,
            -- Exact time this row was loaded
            GETDAte(),
            -- Record hash using SHA2_256
            -- Combines all columns into one fingerprint
            -- If same row loaded twice hash will match
            -- We can detect duplicates using this hash
            HASHBYTES('SHA2_256',
                ISNULL(App_Id,'')           +
                ISNULL(Customer_Name,'')    +
                ISNULL(Date_Of_Birth,'')     +
                ISNULL(PAN_No,'')           +
                ISNULL(Decision,'')         +
                ISNULL(Loan_Amount,'')
                ),

            -- All 24 original columns from raw
            -- Copied exactly as they are
            -- No transformations here
            App_Id,
            Customer_Name,
            Date_Of_Birth,
            PAN_No,
            Product,
            Campaign_Type,
            Decision,
            Decision_Date,
            Stage,
            Decline_Code,
            Sourcing_Channel,
            DSA_Code,
            DSE_Code,
            Secondary_DSE_Code,
            Scheme_Id,
            Appl_Running_Serial_No,
            Signed_Date,
            Sourcing_Branch_Code,
            Residence_City,
            Fee_Code,
            Loan_Amount,
            Mailing_City,
            Type_Of_Organization,
            You_Are

        FROM raw.applications
        WHERE
            -- This is the watermark filter
            -- FULL load : @watermark_start = '0'
            --             loads all rows
            -- INCR load : loads only new rows
            --             where App_Id > last run
            CAST(App_Id as INT) > CAST(@watermark_start as INT);

        -- Capture how many rows were just loaded
        SET @rows_loaded = @@ROWCOUNT;

        PRINT 'Rows loaded to bronze : ' + CAST(@rows_loaded as VARCHAR);

        -- =========================================
        -- Step 5 : Mask PII into masked_attributes
        -- Read from bronze.applications
        -- only rows loaded in this batch
        -- Apply 4 masking rules
        -- Write to bronze.masked_attributes
        -- =========================================

        INSERT INTO bronze.masked_attributes(
            App_Id,
            masked_name,
            masked_pan,
            birth_year,
            masked_dse_code,
            masked_secondary_dse
        )
        SELECT App_Id,

            -- Masking Rule 1 : Customer Name
            -- Take first letter of first word
            -- Take first letter of last word
            -- Example: RAJEEV RAMADHAR SINGH → R.S
            LEFT(Customer_Name, 1) + '.' + LEFT(REVERSE(LTRIM(RTRIM(Customer_Name))),1),

            -- Masking Rule 2 : PAN Number
            -- Convert to SHA2_256 hash
            -- Original PAN never stored beyond raw
            -- Example: APSPS2220M → 7f3a9b2c...

            CONVERT(
                VARCHAR(64),
                HASHBYTES('SHA2_256', ISNULL(PAN_No,'')),2
            ),

            -- Masking Rule 3 : Date of Birth
            -- Extract year only from DOB string
            -- Example: 07-05-75 → 1975
            -- We add 1900 because source has 2 digit year

            CASE
                WHEN CAST(RIGHT(Date_Of_Birth,2) AS INT) > 24
                THEN 1900 + CAST(RIGHT(Date_Of_Birth,2) AS INT)
                ELSE 2000 + CAST(RIGHT(Date_Of_Birth,2) AS INT)
            END,

            -- Masking Rule 4 : DSE Code
            -- Look up pseudonym from agent_pseudonym table
            -- If not found use original code temporarily
            -- Bronze load proc will add new codes later

            ISNULL(ap1.pseudo_code, Dse_Code),

            -- Masking Rule 4 applied to Secondary DSE
            ISNULL(ap2.pseudo_code, Secondary_DSE_CODE)

        FROM bronze.applications b
        -- Join to get DSE pseudonym
        LEFT JOIN audit.agent_pseudonym ap1
            ON b.DSE_Code = ap1.real_code
        LEFT JOIN audit.agent_pseudonym ap2
            ON b.Secondary_DSE_Code = ap2.real_code
         -- Only process rows from this batch
         WHERE b.batch_id = @run_id;

         PRINT 'PII masking complete for batch : ' + CAST(@run_id as VARCHAR);

        -- =========================================
        -- Step 6 : Update Watermark
        -- Save highest App_Id loaded this run
        -- as new watermark for next run
        -- This only runs if we reach this point
        -- meaning Steps 1-5 all succeeded
        -- If anything failed above we never
        -- reach this step — CATCH handles it
        -- =========================================

        -- Find highest App_Id loaded this batch
        -- This becomes starting point for next run

        SELECT @watermark_end = MAX(CAST(App_Id AS INT))
        FROM bronze.applications
        WHERE batch_id = @run_id;
        
      -- Update watermark table with new value
      UPDATE audit.watermark_control
      SET
        last_watermark  = @watermark_end,
        last_run_id     = @run_id,
        last_run_status = 'SUCCESS',
        updated_at      = GETDATE()
      WHERE pipeline_name = 'applications';

      PRINT 'WATERMARK UPDATE TO'

        -- =========================================
        -- Step 7 : Log Pipeline Success
        -- Update pipeline_run_log
        -- Set end_time and status to SUCCESS
        -- Save row counts for reconciliation
        -- This is the last step in TRY block
        -- If we reach here everything worked
        -- =========================================
        UPDATE audit.pipeline_run_log
        SET
            -- Record when pipeline finished
            end_time            = GETDATE(),

            -- Mark as SUCCESS
            status          = 'SUCCESS',

            -- How many rows loaded to bronze
            rows_ingested           = @rows_loaded,

            -- Save watermark values for reference
            watermark_start     = @watermark_start,
            watermark_end       = @watermark_end

        WHERE run_id    = @run_id;

        PRINT 'Pipeline completed successfully';
        PRINT 'Run ID      : ' + CAST(@run_id AS VARCHAR);
        PRINT 'Rows Loaded : ' + CAST(@rows_loaded AS VARCHAR);
        PRINT 'Watermark   : ' + @watermark_end;

    -- =========================================
    -- Close TRY block
    -- If we reach END TRY everything succeeded
    -- =========================================
    END TRY

    -- =========================================
    -- CATCH Block
    -- This runs ONLY if something fails
    -- in the TRY block above
    -- It does 3 things:
    -- 1. Rollback any partial changes
    -- 2. Log failure to pipeline_run_log
    -- 3. Update watermark as FAILED
    -- =========================================
    BEGIN CATCH
        -- Step 1 : Capture error message
        -- ERROR_MESSAGE() is built in SQL Server
        -- It captures exact error that occurred
        SET @error_message = ERROR_MESSAGE();
        
        -- Step 2 : Update pipeline log as FAILED
        -- We still have @run_id from Step 1
        -- Even though TRY failed run_id exists
        -- because Step 1 was first thing we did
        UPDATE audit.pipeline_run_log
        SET
            end_time        =   GETDATE(),
            status          =   'FAILED',
            error_message   =   @error_message
        WHERE run_id = @run_id;

        -- Step 3 : Update watermark as FAILED
        -- Watermark value does NOT change
        -- Only status changes to FAILED
        -- Next run will reprocess same rows
        UPDATE audit.watermark_control
        SET
            last_run_id     = @run_id,
            last_run_status = 'FAILED',
            updated_at      = GETDATE()
        WHERE pipeline_name = 'applications';
        
        -- Step 4 : Raise the error
        -- This sends error back to caller
        -- So master pipeline knows it failed
        THROW;
    END CATCH

-- =========================================
-- Close Procedure
-- =========================================
END
GO

-- Increase You_Are column size in bronze table
-- Raw table already has VARCHAR(200)
-- Bronze must match same size

USE IndusLoanDB;
GO

ALTER TABLE bronze.applications
ALTER COLUMN You_Are VARCHAR(200);
GO

PRINT 'You_Are column updated to VARCHAR(200)';
GO

-- Execute Bronze load procedure
-- First run so we use FULL load
-- This will load all 22155 rows from raw
-- Mask all PII columns
-- Log run to audit.pipeline_run_log

EXEC bronze.usp_load_bronze
    @p_load_type = 'FULL',
    @p_run_date  = NULL,
    @p_env       = 'DEV';
GO

-- Verify bronze load results